language: csharp
solution: SpyStore.sln
mono: none
dotnet: 2.1.801
script:
 - dotnet restore
 - dotnet build
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "arnoldwilliams"
  - git config --local user.email "arnoldwilliams@hotmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: 7s9l9RU_vZx180VyCqwmHQ
  # file: "FILE TO UPLOAD"
  file_glob: true
  file: bin/*
  skip_cleanup: true
on:
  tags: true